/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   'var(--color-primary)',
        'primary-container':         'var(--color-primary-container)',
        'primary-fixed':             'var(--color-primary-fixed)',
        'primary-fixed-dim':         'var(--color-primary-fixed-dim)',
        'on-primary':                'var(--color-on-primary)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'on-primary-fixed':          'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':  'var(--color-on-primary-fixed-variant)',
        'inverse-primary':           'var(--color-inverse-primary)',
        'surface-tint':              'var(--color-surface-tint)',

        'secondary':                 'var(--color-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        'secondary-fixed':           'var(--color-secondary-fixed)',
        'secondary-fixed-dim':       'var(--color-secondary-fixed-dim)',
        'on-secondary':              'var(--color-on-secondary)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'on-secondary-fixed':        'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant':'var(--color-on-secondary-fixed-variant)',

        'tertiary':                  'var(--color-tertiary)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'tertiary-fixed':            'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim':        'var(--color-tertiary-fixed-dim)',
        'on-tertiary':               'var(--color-on-tertiary)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        'on-tertiary-fixed':         'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',

        'surface':                   'var(--color-surface)',
        'surface-bright':            'var(--color-surface-bright)',
        'surface-dim':               'var(--color-surface-dim)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-variant':           'var(--color-surface-variant)',
        'inverse-surface':           'var(--color-inverse-surface)',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',

        'background':                'var(--color-background)',
        'on-background':             'var(--color-on-background)',
        'on-surface':                'var(--color-on-surface)',
        'on-surface-variant':        'var(--color-on-surface-variant)',

        'outline':                   'var(--color-outline)',
        'outline-variant':           'var(--color-outline-variant)',

        'error':                     'var(--color-error)',
        'error-container':           'var(--color-error-container)',
        'on-error':                  'var(--color-on-error)',
        'on-error-container':        'var(--color-on-error-container)',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
